#!/bin/sh
NODE_EXEC=<%=nodeExec%>
NODE_ENV="production"
NODE_APP=<%=nodeApplication%>
APP_DIR=<%=appDir%>
PID_FILE=/var/run/<%=name%>.pid
LOG_FILE=/var/log/<%=name%>.log
CONFIG_DIR=$APP_DIR/config

###############

#REDHAT chkconfig header

# chkconfig: - 58 74
# description: <%=description%>
### BEGIN INIT INFO
# Provides: node
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop nodehosting
# Description: <%=description%>
### END INIT INFO


case "$1" in
    start)
        if [ -f $PID_FILE ]
        then
                echo "$PID_FILE exists, process is already running or crashed"
        else
                echo "Starting <%=name%> ..."
                NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $NODE_APP  1>$LOG_FILE 2>&1 &
                echo $! > $PID_FILE;
        fi
        ;;

    stop)
        if [ ! -f $PID_FILE ]
        then
                echo "$PID_FILE does not exist, process is not running"
        else
                echo "Stopping $NODE_APP ..."
                echo "Killing `cat $PID_FILE`"
                kill `cat $PID_FILE`;
                rm $PID_FILE;
                echo "<%=name%> stopped"
        fi
        ;;

        restart)
                if [ ! -f $PID_FILE ]
                then
                        echo "$PID_FILE does not exist, process is not running"

                else
                        echo "Restarting $NODE_APP ..."
                        echo "Killing `cat $PID_FILE`"
                        kill `cat $PID_FILE`;
                        rm $PID_FILE;
                        NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $NODE_APP  1>$LOG_FILE 2>&1 &
                        echo $! > $PID_FILE;
                        echo "<%=name%> started"
                fi
                ;;

        status)
        if [ -f $PID_FILE ]
        then
            PID=`cat $PID_FILE`
            if [ -z "`ps -ef | grep $PID | grep -v grep`" ]
            then
                echo "<%=name%> stopped but pid file exists"
            else
                echo "<%=name%> running with pid $PID"

            fi
        else
            echo "<%=name%> stopped"
        fi
        ;;

        *)
                echo "Usage: /etc/init.d/<%=name%> {start|stop|restart|status}"
        ;;
esac